version: "3"

services:

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - my_data1:/root/.lnd
      - my_data2:/root/.lnd2
    networks:
      default:
        ipv4_address: 172.28.0.2
    depends_on:
      - thought
      - rippled
      - geth
      - ganache

  thoughtd:
    container_name: thoughtd-crypto-rpc
    image: thoughtd:0.18.3
    build:
      context: .
      dockerfile: ./Thought/Dockerfile
    ports:
      - 10617:10617
      - 10618:10618
      - 11617:11617
      - 11618:11618
    restart: unless-stopped

  geth:
    image: 0labs/geth:v1.10.21
    volumes:
      - ./tests/docker/geth-keystore:/keystore
    ports:
      - "9545:8545"
    networks:
      default:
        ipv4_address: 172.28.0.7
    command: geth --dev --datadir=/home/kjoseph/nodes/dev/geth --networkid=1337 --http --http.api=web3,eth,debug,personal,net --http.corsdomain='*' --http.vhosts='*' --http.addr=0.0.0.0 --http.port=8545 --keystore=/keystore --allow-insecure-unlock --unlock=00a329c0648769a73afac7f9381e08fb43dbea72 --password=/keystore/pw

  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - "10545:8545"
    networks:
      default:
        ipv4_address: 172.28.0.11
    command: -m "dose youth patient boring disagree tuna random tower tornado version violin around" -b 2 -g 20000000000 -p 8545 -a 20

volumes:
  my_data1:
    driver: local
  my_data2:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
